version: '3.1'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: posts
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - default

  app:
    image: node:21-alpine
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    command: /bin/sh -c "npm install && npm run dev"
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    networks:
      - default

networks:
  default:
